from .patients_await_entrance import patients_await_entrance_api
from .referred_patients import referred_patients_api
from .awaits_opening import awaits_opening_api
from .awaits_approval import awaits_approval_api
from .referrals_history import referrals_history_api
from .active_internemnts import active_internments_api
from .internment_history import internment_history_api
