from .typology_stats import TypologyStatsAdmin
from .typology_ii_monthly_stats import TypologyIIMonthlyStatsAdmin
from .monthly_invoice import MonthlyInvoiceAdmin
from .yearly_invoice import YearlyInvoiceAdmin
from .daily_value import DailyValueAdmin
