# Generated by Django 4.0.3 on 2022-03-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
