# Generated by Django 4.0.3 on 2022-04-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('user_management', '0004_customuser_care_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='care_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.carehouse'),
        ),
    ]
