# Generated by Django 4.0.3 on 2022-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_customuser_care_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Institution Psychiatrist'), ('reviewer', 'Referral Reviewer'), ('care_house_staff', 'Care House Staff'), ('financial', 'Financial Staff'), ('superuser', 'Superuser')], max_length=16),
        ),
    ]
