# Generated by Django 4.0.3 on 2022-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_notificationtemplate_remove_notifications_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('referral_creation', 'Criação de Referenciação'), ('referral_opening_indication', 'Indicação de Vaga'), ('referral_evaluation', 'Avaliação de Referenciação'), ('receipt_creation', 'Criação de Recibo'), ('receipt_evaluation', 'Avaliação de Recibo')], max_length=27),
        ),
    ]
