# Generated by Django 4.0.3 on 2022-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_notifications_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('referral_creation', 'Criação de Referenciação'), ('referral_opening_indication', 'Indicação de Vaga'), ('referral_evaluation', 'Avaliação de Referenciação'), ('invoice_creation', 'Criação de Recibo'), ('invoice_evaluation', 'Avaliação de Recibo')], max_length=27),
        ),
    ]
