# Generated by Django 4.0.3 on 2022-04-02 13:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('next_states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None)),
                ('prev_states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('sns_number', models.CharField(max_length=10, unique=True)),
                ('social_security_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('typology', models.CharField(max_length=3)),
                ('admission_diagnosis', models.CharField(max_length=256)),
                ('process_number', models.CharField(max_length=25, unique=True)),
                ('responsibility_term', models.FileField(upload_to='')),
                ('supervision_scale', models.FileField(upload_to='')),
                ('family_situation', models.CharField(max_length=256)),
                ('relative_name', models.CharField(blank=True, max_length=256, null=True)),
                ('relative_kinship', models.CharField(blank=True, max_length=256, null=True)),
                ('relative_contact', models.CharField(blank=True, max_length=256, null=True)),
                ('social_assistant', models.CharField(blank=True, max_length=256, null=True)),
                ('supervision_grade', models.CharField(choices=[('1', '1 - Sem Supervisão'), ('2', '2 - Sem Supervisão'), ('3', '3 - Sem Supervisão'), ('4', '4 - Sem Supervisão')], max_length=2)),
                ('referral_motive', models.TextField()),
                ('other_diagnosis', models.TextField(blank=True)),
                ('social_situation', models.CharField(max_length=256)),
                ('internment_duration', models.CharField(choices=[], max_length=25)),
                ('medication', models.TextField()),
                ('referral_date', models.DateTimeField()),
                ('approval_date', models.DateTimeField(null=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internment_management.internmentstatus')),
                ('origin_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.medicalinstitution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internment_management.patient')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareHouseInternment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('admission_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('reason_to_leave', models.CharField(choices=[], max_length=25)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('care_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.carehouse')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internment_management.internmentstatus')),
                ('patients', models.ManyToManyField(blank=True, to='internment_management.patient')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internment_management.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('action', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('log_date', models.DateTimeField()),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internment_management.carehouseinternment')),
            ],
        ),
    ]
