# Generated by Django 4.0.3 on 2022-04-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('internment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='care_house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.carehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='typology',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=3),
        ),
    ]
