# Generated by Django 4.0.3 on 2022-04-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0002_referral_care_house_alter_referral_typology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carehouseinternment',
            name='care_house',
        ),
        migrations.RemoveField(
            model_name='carehouseinternment',
            name='patients',
        ),
    ]
