# Generated by Django 4.0.3 on 2022-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0003_remove_carehouseinternment_care_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internmentstatus',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
