# Generated by Django 4.0.3 on 2022-04-05 20:43

from django.db import migrations, models
import internment_management.utils.referral_files_path


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0004_alter_internmentstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='responsibility_term',
            field=models.FileField(upload_to=internment_management.utils.referral_files_path.referral_files_path),
        ),
        migrations.AlterField(
            model_name='referral',
            name='supervision_scale',
            field=models.FileField(upload_to=internment_management.utils.referral_files_path.referral_files_path),
        ),
    ]
