# Generated by Django 4.0.3 on 2022-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0005_alter_referral_responsibility_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='internment_duration',
            field=models.CharField(choices=[('short', 'Curta Duração'), ('medium', 'Média Duração'), ('long', 'Longa Duração')], max_length=25),
        ),
    ]
