# Generated by Django 4.0.3 on 2022-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0006_alter_referral_internment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='supervision_grade',
            field=models.CharField(choices=[('1', 'Sem/Pouca Supervisão'), ('2', 'Bastante/Muita Supervisão'), ('3', 'Alta Supervisão')], max_length=2),
        ),
    ]
