# Generated by Django 4.0.3 on 2022-04-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0007_alter_referral_supervision_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='disease_type',
            field=models.CharField(choices=[('1', '1 - Rabilitação'), ('2', '2 - Alcoologia'), ('3', '3 - Agudos'), ('4', '4 - Psicogeriatria'), ('5', '5 - Psiquiatria Longa Duração')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
