# Generated by Django 4.0.3 on 2022-04-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0008_referral_disease_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='internmentstatus',
            name='type',
            field=models.CharField(choices=[('referral', 'Referral'), ('internment', 'Internment')], default='referral', max_length=10),
        ),
    ]
