# Generated by Django 4.0.3 on 2022-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0011_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internmentstatus',
            name='label',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
