# Generated by Django 4.0.3 on 2022-05-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0012_alter_internmentstatus_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carehouseinternment',
            name='reason_to_leave',
        ),
    ]
