# Generated by Django 4.0.3 on 2022-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0013_remove_carehouseinternment_reason_to_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='doctor_name',
            field=models.CharField(default='Mr Doctor', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='doctor_professional_certificate',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
