# Generated by Django 4.0.3 on 2022-05-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0014_referral_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('temporary_leave', 'Saída Temporária'), ('return', 'Retorno'), ('exit', 'Saída')], default='entry', max_length=15),
            preserve_default=False,
        ),
    ]
