# Generated by Django 4.0.3 on 2022-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0016_patient_country_patient_gender_patient_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locality',
            field=models.CharField(default='Lisboa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(default='1234-567', max_length=8),
            preserve_default=False,
        ),
    ]
