# Generated by Django 4.0.3 on 2022-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0017_patient_locality_patient_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='subsystem',
            field=models.CharField(default='543', max_length=4),
        ),
    ]
