# Generated by Django 4.0.3 on 2022-12-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internment_management', '0019_alter_patient_subsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
