# Generated by Django 4.0.3 on 2022-04-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypologyIIMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('total_patients', models.IntegerField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TypologyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('typology_stats', models.JSONField()),
                ('care_house_stats', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='YearlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('year', models.PositiveIntegerField()),
                ('total_amount', models.FloatField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('typology', models.CharField(max_length=3)),
                ('invoice_lines', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('care_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.carehouse')),
            ],
        ),
    ]
