# Generated by Django 4.0.3 on 2022-05-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_monthlyinvoice_month_monthlyinvoice_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
