# Generated by Django 4.0.3 on 2022-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_monthlyinvoice_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
