# Generated by Django 4.0.3 on 2022-06-11 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_monthlyinvoice_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='typologystats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typologystats',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
