# Generated by Django 4.0.3 on 2022-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_typologystats_created_typologystats_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typologyiimonthlystats',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')]),
        ),
    ]
