# Generated by Django 4.0.3 on 2022-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_typologyiimonthlystats_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvalue',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
